# # version: '3.8'
# services:
#   nextjs-app:
#     build:
#       context: .
#       dockerfile: ./apps/site/Dockerfile
#     ports:
#       - '3000:3000'
#     environment:
#       - NODE_ENV=production
#       - NEXT_OUTPUT=standalone
#     restart: unless-stopped
#     volumes:
#       - ./apps/site/public:/app/apps/site/public:ro
#     networks:
#       - app-network
#     # depends_on:
#     #   - vite-app
#     # networks:
#     #   - app_network

#   vite-app:
#     build:
#       context: .
#       dockerfile: ./apps/dashboard/Dockerfile
#     ports:
#       - '3001:3000'
#     environment:
#       - NODE_ENV=production
#     restart: unless-stopped
#     volumes:
#       - ./apps/dashboard/dist:/app/apps/dashboard/dist:ro
#     networks:
#       - app_network
#     depends_on:
#       - nextjs-app

# # Defina uma rede, que permite que os contêineres se comuniquem
# # entre si, usando o nome do contêiner como um nome de host
# networks:
#   app-network:
#     name: app_network
#     driver: bridge
# # networks:
# #   app_network:
# #     external: true
# version: '3.8'

# services:
#   nextjs-app:
#     build:
#       context: .
#       dockerfile: ./apps/site/Dockerfile
#     container_name: nextjs-app
#     ports:
#       - '3000:3000'
#     environment:
#       - NODE_ENV=production
#       - NEXT_OUTPUT=standalone
#     restart: unless-stopped
#     volumes:
#       - ./apps/site/public:/app/apps/site/public:ro
#     networks:
#       - app_network

#   vite-app:
#     build:
#       context: .
#       dockerfile: ./apps/dashboard/Dockerfile
#     container_name: vite-app
#     ports:
#       - '3001:3000'
#     environment:
#       - NODE_ENV=production
#       - VITE_API_URL=http://nextjs-app:3000
#     restart: unless-stopped
#     volumes:
#       - ./apps/dashboard/dist:/app/apps/dashboard/dist:ro
#     networks:
#       - app_network
#     depends_on:
#       - nextjs-app

# networks:
#   app_network:
#     driver: bridge

# version: '3.8'

# services:
#   nextjs-app:
#     build:
#       context: .
#       dockerfile: ./apps/site/Dockerfile
#     container_name: nextjs-app
#     ports:
#       - '3000:3000'
#     environment:
#       - NODE_ENV=production
#     networks:
#       - app_network

#   vite-app:
#     build:
#       context: .
#       dockerfile: ./apps/dashboard/Dockerfile
#     container_name: vite-app
#     ports:
#       - '3001:3000'
#     depends_on:
#       - nextjs-app
#     networks:
#       - app_network
#     environment:
#       - VITE_API_BASE_URL=http://nextjs-app:3000/api
#     environment:
#       - NEXTJS_SERVICE_NAME=nextjs-app
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:3000"]
#       interval: 30s
#       timeout: 5s
#       retries: 3
#     depends_on:
#       nextjs-app:
#         condition: service_healthy

# networks:
#   app_network:
#     driver: bridge

version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: ./apps/site/Dockerfile
    container_name: nextjs-app
    ports:
      - '3000:3000'
    networks:
      - app_network

  vite-app:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    container_name: vite-app
    ports:
      - '3001:3000'
    depends_on:
      - nextjs-app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
