name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js App
      working-directory: ./apps/site
      run: npm run build

    - name: Build Vite App
      working-directory: ./apps/dashboard
      run: npm run build

    - name: Deploy Next.js to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_NEXTJS }}
        working-directory: ./apps/site
        vercel-args: '--prod'
        github-comment: true
        github-deployment: false

    - name: Deploy Vite App to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_VITE }}
        working-directory: ./apps/dashboard
        vercel-args: '--prod'
        github-comment: true
        github-deployment: false